import PDFDocument from 'pdfkit';
import ExcelJS from 'exceljs';

export class ExportService {
  /**
   * Generates a Landscape PDF document with formatted tables and headers.
   */
  async generatePDF(
    title: string,
    headers: string[],
    rows: any[][],
    filters: any,
    userEmail: string
  ): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ layout: 'landscape', margin: 30 });
        const buffers: Buffer[] = [];
        doc.on('data', (chunk) => buffers.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', (err) => reject(err));

        // Header Branding
        doc.fontSize(16).font('Helvetica-Bold').text('AssetFlow Enterprise ERP', { align: 'center' });
        doc.fontSize(12).font('Helvetica').text(title, { align: 'center' });
        doc.moveDown(1);

        // Metadata Box
        doc.fontSize(8).font('Helvetica-Oblique').text(`Generated By: ${userEmail}`);
        doc.text(`Generated At: ${new Date().toISOString()}`);
        doc.text(`Applied Filters: ${JSON.stringify(filters)}`);
        doc.moveDown(1.5);

        // Table Setup
        const startX = 30;
        let startY = doc.y;
        const colWidth = (doc.page.width - 60) / headers.length;

        // Draw Headers
        doc.fontSize(9).font('Helvetica-Bold');
        headers.forEach((h, idx) => {
          doc.text(h, startX + idx * colWidth, startY, { width: colWidth, align: 'left' });
        });
        doc.moveDown(0.5);
        doc.font('Helvetica');

        // Draw Line separator
        doc.moveTo(startX, doc.y).lineTo(doc.page.width - 30, doc.y).stroke();
        doc.moveDown(0.5);

        // Draw Data Rows
        rows.forEach(row => {
          startY = doc.y;
          if (startY > doc.page.height - 50) {
            doc.addPage();
            startY = doc.y;
          }
          row.forEach((cell, idx) => {
            doc.text(String(cell !== null && cell !== undefined ? cell : ''), startX + idx * colWidth, startY, {
              width: colWidth,
              align: 'left'
            });
          });
          doc.moveDown(0.5);
        });

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  /**
   * Generates a styled Excel workbook with title, metadata, and auto-adjusted columns.
   */
  async generateExcel(
    title: string,
    headers: string[],
    rows: any[][],
    filters: any,
    userEmail: string
  ): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Report');

    // Title Row
    worksheet.addRow(['AssetFlow Enterprise ERP']).font = { bold: true, size: 16 };
    worksheet.addRow([title]).font = { bold: true, size: 12 };
    worksheet.addRow([]);

    // Metadata
    worksheet.addRow([`Generated By: ${userEmail}`]);
    worksheet.addRow([`Generated At: ${new Date().toISOString()}`]);
    worksheet.addRow([`Applied Filters: ${JSON.stringify(filters)}`]);
    worksheet.addRow([]);

    // Header Row
    const headerRow = worksheet.addRow(headers);
    headerRow.font = { bold: true };
    headerRow.eachCell(cell => {
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFE0E0E0' }
      };
      cell.border = {
        bottom: { style: 'thin' }
      };
    });

    // Data Rows
    rows.forEach(r => worksheet.addRow(r));

    // Auto-fit column widths
    worksheet.columns.forEach(column => {
      let maxLen = 0;
      if (column.eachCell) {
        column.eachCell({ includeEmpty: true }, cell => {
          const valLen = cell.value ? String(cell.value).length : 0;
          if (valLen > maxLen) maxLen = valLen;
        });
      }
      column.width = Math.max(maxLen + 2, 10);
    });

    const buffer = await workbook.xlsx.writeBuffer() as any as Buffer;
    return buffer;
  }

  /**
   * Generates standard comma-separated values (CSV) string.
   */
  generateCSV(headers: string[], rows: any[][]): string {
    const escapeVal = (val: any) => {
      const s = String(val !== null && val !== undefined ? val : '');
      if (s.includes(',') || s.includes('"') || s.includes('\n')) {
        return `"${s.replace(/"/g, '""')}"`;
      }
      return s;
    };

    const headerLine = headers.map(escapeVal).join(',');
    const rowLines = rows.map(r => r.map(escapeVal).join(','));
    return [headerLine, ...rowLines].join('\n');
  }
}

export default ExportService;
