/**
 * activity-log.constants.ts — Action categories and action names for Audit Trail logs.
 */

export const ACTIVITY_ACTIONS = {
  // Authentication
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  RESET_PASSWORD: 'RESET_PASSWORD',

  // Employee / Dept Setup
  EMPLOYEE_CREATED: 'EMPLOYEE_CREATED',
  EMPLOYEE_UPDATED: 'EMPLOYEE_UPDATED',
  EMPLOYEE_ROLE_CHANGED: 'EMPLOYEE_ROLE_CHANGED',
  DEPARTMENT_CREATED: 'DEPARTMENT_CREATED',
  DEPARTMENT_UPDATED: 'DEPARTMENT_UPDATED',

  // Asset Management
  ASSET_CREATED: 'ASSET_CREATED',
  ASSET_UPDATED: 'ASSET_UPDATED',
  ASSET_DISPOSED: 'ASSET_DISPOSED',
  ASSET_DEPRECIATED: 'ASSET_DEPRECIATED',

  // Allocation & Transfer
  ASSET_ALLOCATED: 'ASSET_ALLOCATED',
  ASSET_RETURNED: 'ASSET_RETURNED',
  TRANSFER_REQUESTED: 'TRANSFER_REQUESTED',
  TRANSFER_APPROVED: 'TRANSFER_APPROVED',
  TRANSFER_REJECTED: 'TRANSFER_REJECTED',

  // Booking
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_RESCHEDULED: 'BOOKING_RESCHEDULED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_STATUS_CHANGED: 'BOOKING_STATUS_CHANGED',

  // Maintenance
  MAINTENANCE_REQUESTED: 'MAINTENANCE_REQUESTED',
  MAINTENANCE_APPROVED: 'MAINTENANCE_APPROVED',
  MAINTENANCE_REJECTED: 'MAINTENANCE_REJECTED',
  MAINTENANCE_STARTED: 'MAINTENANCE_STARTED',
  MAINTENANCE_COMPLETED: 'MAINTENANCE_COMPLETED',
  MAINTENANCE_CLOSED: 'MAINTENANCE_CLOSED',
  MAINTENANCE_CANCELLED: 'MAINTENANCE_CANCELLED',

  // Audit
  AUDIT_CREATED: 'AUDIT_CREATED',
  AUDIT_UPDATED: 'AUDIT_UPDATED',
  AUDIT_DELETED: 'AUDIT_DELETED',
  AUDIT_AUDITORS_ASSIGNED: 'AUDIT_AUDITORS_ASSIGNED',
  AUDIT_STARTED: 'AUDIT_STARTED',
  AUDIT_ASSET_VERIFIED: 'AUDIT_ASSET_VERIFIED',
  AUDIT_COMPLETED: 'AUDIT_COMPLETED',
  AUDIT_CLOSED: 'AUDIT_CLOSED',
  AUDIT_CANCELLED: 'AUDIT_CANCELLED'
} as const;

export type ActivityAction = typeof ACTIVITY_ACTIONS[keyof typeof ACTIVITY_ACTIONS];

export const ACTIVITY_MODULES = {
  AUTH: 'Auth',
  ORGANIZATION: 'Organization',
  ASSET: 'Asset',
  ALLOCATION: 'Allocation',
  BOOKING: 'Booking',
  MAINTENANCE: 'Maintenance',
  AUDIT: 'Audit'
} as const;

export type ActivityModule = typeof ACTIVITY_MODULES[keyof typeof ACTIVITY_MODULES];
